---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: terraform
- name: scf-tutorial

outputs:
- name: tf-metadata-to-file

run:
  path: scf-tutorial/ci/tasks/tf-metadata-to-file.sh

params:
  METADATA_KEY:
  OUTPUT_FILE:
