---
apiVersion: "v1"
data:
  # Password used for the active uaa encryption key.
  aek-password: ""

  # PEM-encoded CA certificate used to sign the TLS certificate used by all
  # components to secure their communications.
  internal-ca-cert: ""

  # PEM-encoded CA key.
  internal-ca-cert-key: ""

  # PEM-encoded JWT certificate.
  jwt-signing-cert: ""

  # PEM-encoded JWT signing key.
  jwt-signing-cert-key: ""

  # Password used for the monit API.
  monit-password: ""

  # The password for the MySQL server admin user.
  mysql-admin-password: ""

  # The password for the cluster logger health user.
  mysql-cluster-health-password: ""

  # The password used to contact the sidecar endpoints via Basic Auth.
  mysql-galera-healthcheck-endpoint-password: ""

  # The password for Basic Auth used to secure the MySQL proxy API.
  mysql-proxy-admin-password: ""

  # PEM-encoded certificate
  saml-serviceprovider-cert: ""

  # PEM-encoded key.
  saml-serviceprovider-cert-key: ""

  # The password of the admin client - a client named admin with uaa.admin as an
  # authority.
  uaa-admin-client-secret: ""

  # The server's ssl certificate. The default is a self-signed certificate and
  # should always be replaced for production deployments.
  uaa-server-cert: ""

  # The server's ssl private key. Only passphrase-less keys are supported.
  uaa-server-cert-key: ""

  # The password for access to the UAA database.
  uaadb-password: ""

kind: "Secret"
metadata:
  name: "secrets"
  labels:
    app.kubernetes.io/component: "secrets"
