---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: persistent
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/host-path
parameters:
  path: /tmp
