---
# The acceptance-tests instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - acceptance-tests: The acceptance tests errand can be configured to run full
#   acceptance test suite against a specific Cloud Foundry API endpoint.
#   Consider running smoke tests errand for a smaller set of tests.
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "acceptance-tests"
  labels:
    app.kubernetes.io/component: "acceptance-tests"
spec:
  containers:
  - env:
    - name: "ACCEPTANCE_TEST_NODES"
      value: "4"
    - name: "AZ_LABEL_NAME"
      value: ""
    - name: "CATS_SUITES"
      value: ""
    - name: "CLUSTER_ADMIN_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "cluster-admin-password"
          name: "secrets"
    - name: "DOMAIN"
      value: ""
    - name: "GARDEN_ROOTFS_DRIVER"
      value: "btrfs"
    - name: "INTERNAL_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert"
          name: "secrets"
    - name: "INTERNAL_CA_CERT_KEY"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert-key"
          name: "secrets"
    - name: "KUBERNETES_CLUSTER_DOMAIN"
      value: ""
    - name: "KUBERNETES_NAMESPACE"
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: "MONIT_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "monit-password"
          name: "secrets"
    - name: "PZ_LABEL_NAME"
      value: ""
    - name: "SCF_LOG_HOST"
      value: ""
    - name: "SCF_LOG_PORT"
      value: "514"
    - name: "SCF_LOG_PROTOCOL"
      value: "tcp"
    - name: "UAA_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "uaa-ca-cert"
          name: "secrets"
    - name: "VCAP_HARD_NPROC"
      value: "2048"
    - name: "VCAP_SOFT_NPROC"
      value: "1024"
    image: "registry.suse.com/cap/scf-acceptance-tests:e78f2e27f19c16858d7000f979e599b9cd925307"
    lifecycle:
      preStop:
        exec:
          command:
          - "/opt/fissile/pre-stop.sh"
    livenessProbe: ~
    name: "acceptance-tests"
    ports: ~
    readinessProbe: ~
    resources:
      requests: {}
      limits: {}
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: "/opt/fissile/config"
      name: "deployment-manifest"
      readOnly: true
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "registry-credentials"
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 600
  volumes:
  - name: "deployment-manifest"
    secret:
      secretName: "deployment-manifest"
      items:
      - key: "deployment-manifest"
        path: "deployment-manifest.yml"
