---
# The acceptance-tests-brain instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - acceptance-tests-brain: This job will run the testbrain CLI, running all
#   acceptance test scripts in src/testbrain/test-scripts
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "acceptance-tests-brain"
  labels:
    app.kubernetes.io/component: "acceptance-tests-brain"
spec:
  containers:
  - env:
    - name: "AUTOSCALER_SERVICE_BROKER_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "autoscaler-service-broker-password"
          name: "secrets"
    - name: "AZ_LABEL_NAME"
      value: ""
    - name: "CATS_SUITES"
      value: ""
    - name: "CLUSTER_ADMIN_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "cluster-admin-password"
          name: "secrets"
    - name: "DOMAIN"
      value: ""
    - name: "GARDEN_ROOTFS_DRIVER"
      value: "btrfs"
    - name: "INTERNAL_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert"
          name: "secrets"
    - name: "KUBERNETES_CLUSTER_DOMAIN"
      value: ""
    - name: "KUBERNETES_NAMESPACE"
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: "KUBERNETES_STORAGE_CLASS_PERSISTENT"
      value: "persistent"
    - name: "MONIT_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "monit-password"
          name: "secrets"
    - name: "PZ_LABEL_NAME"
      value: ""
    - name: "SCF_LOG_HOST"
      value: ""
    - name: "SCF_LOG_PORT"
      value: "514"
    - name: "SCF_LOG_PROTOCOL"
      value: "tcp"
    - name: "TCP_DOMAIN"
      value: ""
    - name: "UAA_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "uaa-ca-cert"
          name: "secrets"
    - name: "VCAP_HARD_NPROC"
      value: "2048"
    - name: "VCAP_SOFT_NPROC"
      value: "1024"
    image: "registry.suse.com/cap/scf-acceptance-tests-brain:d31672314fbca3ea51fd497468034eff6d92c704"
    lifecycle:
      preStop:
        exec:
          command:
          - "/opt/fissile/pre-stop.sh"
    livenessProbe: ~
    name: "acceptance-tests-brain"
    ports: ~
    readinessProbe: ~
    resources:
      requests: {}
      limits: {}
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: "/opt/fissile/config"
      name: "deployment-manifest"
      readOnly: true
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "registry-credentials"
  restartPolicy: "Never"
  serviceAccountName: "tests"
  terminationGracePeriodSeconds: 600
  volumes:
  - name: "deployment-manifest"
    secret:
      secretName: "deployment-manifest"
      items:
      - key: "deployment-manifest"
        path: "deployment-manifest.yml"
