---
# The smoke-tests instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - smoke_tests: The smoke tests errand can be configured to run quick set of
#   tests against a specific Cloud Foundry API endpoint to determine is basic
#   push-application functionality works. Consider running the acceptance tests
#   errand for a more extensive set of tests.
#
# Also: cf-cli-6-linux and bpm
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "smoke-tests"
  labels:
    app.kubernetes.io/component: "smoke-tests"
spec:
  containers:
  - env:
    - name: "AZ_LABEL_NAME"
      value: ""
    - name: "CATS_SUITES"
      value: ""
    - name: "CLUSTER_ADMIN_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "cluster-admin-password"
          name: "secrets"
    - name: "DOMAIN"
      value: ""
    - name: "GARDEN_ROOTFS_DRIVER"
      value: "btrfs"
    - name: "INTERNAL_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert"
          name: "secrets"
    - name: "KUBERNETES_CLUSTER_DOMAIN"
      value: ""
    - name: "KUBERNETES_NAMESPACE"
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: "MONIT_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "monit-password"
          name: "secrets"
    - name: "PZ_LABEL_NAME"
      value: ""
    - name: "SCF_LOG_HOST"
      value: ""
    - name: "SCF_LOG_PORT"
      value: "514"
    - name: "SCF_LOG_PROTOCOL"
      value: "tcp"
    - name: "UAA_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "uaa-ca-cert"
          name: "secrets"
    - name: "VCAP_HARD_NPROC"
      value: "2048"
    - name: "VCAP_SOFT_NPROC"
      value: "1024"
    image: "registry.suse.com/cap/scf-smoke-tests:8cc565fe7bb9f0ab04dfa757f9da07306ceeb6a3"
    lifecycle:
      preStop:
        exec:
          command:
          - "/opt/fissile/pre-stop.sh"
    livenessProbe: ~
    name: "smoke-tests"
    ports: ~
    readinessProbe: ~
    resources:
      requests: {}
      limits: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: "/opt/fissile/config"
      name: "deployment-manifest"
      readOnly: true
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "registry-credentials"
  restartPolicy: "Never"
  serviceAccountName: "default-privileged"
  terminationGracePeriodSeconds: 600
  volumes:
  - name: "deployment-manifest"
    secret:
      secretName: "deployment-manifest"
      items:
      - key: "deployment-manifest"
        path: "deployment-manifest.yml"
