---
# The sync-integration-tests instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - sync-integration-tests: The sync integration tests errand can be configured
#   to run full sync integration test suite against a specific Cloud Foundry API
#   endpoint.
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "sync-integration-tests"
  labels:
    app.kubernetes.io/component: "sync-integration-tests"
spec:
  containers:
  - env:
    - name: "AZ_LABEL_NAME"
      value: ""
    - name: "BBS_CLIENT_CRT"
      valueFrom:
        secretKeyRef:
          key: "bbs-client-crt"
          name: "secrets"
    - name: "BBS_CLIENT_CRT_KEY"
      valueFrom:
        secretKeyRef:
          key: "bbs-client-crt-key"
          name: "secrets"
    - name: "CATS_SUITES"
      value: ""
    - name: "CLUSTER_ADMIN_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "cluster-admin-password"
          name: "secrets"
    - name: "DOMAIN"
      value: ""
    - name: "GARDEN_ROOTFS_DRIVER"
      value: "btrfs"
    - name: "INTERNAL_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert"
          name: "secrets"
    - name: "INTERNAL_CA_CERT_KEY"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert-key"
          name: "secrets"
    - name: "KUBERNETES_CLUSTER_DOMAIN"
      value: ""
    - name: "KUBERNETES_NAMESPACE"
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: "MONIT_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "monit-password"
          name: "secrets"
    - name: "PZ_LABEL_NAME"
      value: ""
    - name: "SCF_LOG_HOST"
      value: ""
    - name: "SCF_LOG_PORT"
      value: "514"
    - name: "SCF_LOG_PROTOCOL"
      value: "tcp"
    - name: "SYNC_INTEGRATION_TESTS_FOCUS"
      value: ""
    - name: "SYNC_INTEGRATION_TESTS_NODES"
      value: "4"
    - name: "SYNC_INTEGRATION_TESTS_SKIP"
      value: ""
    - name: "SYNC_INTEGRATION_TESTS_VERBOSE"
      value: "false"
    - name: "UAA_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "uaa-ca-cert"
          name: "secrets"
    - name: "VCAP_HARD_NPROC"
      value: "2048"
    - name: "VCAP_SOFT_NPROC"
      value: "1024"
    image: "registry.suse.com/cap/scf-sync-integration-tests:02b16ddfc18e62999cbd6bb36d88307d4c7901be"
    lifecycle:
      preStop:
        exec:
          command:
          - "/opt/fissile/pre-stop.sh"
    livenessProbe: ~
    name: "sync-integration-tests"
    ports: ~
    readinessProbe: ~
    resources:
      requests: {}
      limits: {}
    securityContext:
      allowPrivilegeEscalation: false
    volumeMounts:
    - mountPath: "/opt/fissile/config"
      name: "deployment-manifest"
      readOnly: true
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "registry-credentials"
  restartPolicy: "Never"
  serviceAccountName: "tests"
  terminationGracePeriodSeconds: 600
  volumes:
  - name: "deployment-manifest"
    secret:
      secretName: "deployment-manifest"
      items:
      - key: "deployment-manifest"
        path: "deployment-manifest.yml"
