---
resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.13
- name: helm
  type: docker-image
  source:
    username: ((dockerhub_user))
    password: ((dockerhub_password))
    repository: engineerbetter/concourse-helm-resource
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.14"

resources:
- name: tfstate
  type: gcs-resource
  source:
    bucket: ((project_id))
    json_key: ((gcp_credentials_json))
    versioned_file: ci/terraform.tfstate
- name: concourse-gcp-tf-bootstrap
  type: git
  source:
    uri: https://github.com/EngineerBetter/concourse-gcp-tf-bootstrap.git
    branch: master
- name: scf-tutorial
  type: git
  source:
    uri: https://github.com/EngineerBetter/scf-tutorial.git
    branch: master
- name: gke-tf
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: ((project_id))
      prefix: gke
      region: ((region))
      credentials: ((gcp_credentials_json))
    env:
      GOOGLE_CLOUD_KEYFILE_JSON: ((gcp_credentials_json))
      GOOGLE_PROJECT: ((project_id))
      GOOGLE_REGION: ((region))
      GOOGLE_ZONE: ((zone))
- name: concourse-helm-resource
  type: git
  source:
    uri: https://github.com/linkyard/concourse-helm-resource.git
    branch: master
- name: concourse-helm-resource-image
  type: docker-image
  source:
    repository: engineerbetter/concourse-helm-resource
    username: ((dockerhub_user))
    password: ((dockerhub_password))
- name: helm
  type: helm
  source:
    helm_init_server: true
    helm_init_wait: true
    helm_service_account: helm
    tracing_enabled: true
- name: scf-release
  type: github-release
  source:
    owner: SUSE
    repository: scf
- name: kubernetes
  type: kubernetes

jobs:
- name: setup-project
  plan:
  - get: concourse-gcp-tf-bootstrap
    trigger: true
  - task: bootstrap-terraform
    file: concourse-gcp-tf-bootstrap/tasks/bootstrap.yml
    input_mapping:
      gcp-bootstrap: concourse-gcp-tf-bootstrap
    params: &project-ops-params
      BILLING_ACCOUNT_ID: ((billing_account_id))
      BUCKET_LOCATION: ((region))
      FOLDER_NAME: ((folder_name))
      GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
      ORGANIZATION_ID: ((organization_id))
      PROJECT_ID: ((project_id))
      PROJECT_NAME: ((project_name))
  - put: tfstate
    params:
      file: tfstate-out/terraform.tfstate

- name: teardown-project
  plan:
  - get: concourse-gcp-tf-bootstrap
    passed: [setup-project]
  - get: tfstate
    passed: [setup-project]
  - task: bootstrap-terraform
    file: concourse-gcp-tf-bootstrap/tasks/teardown.yml
    input_mapping:
      gcp-bootstrap: concourse-gcp-tf-bootstrap
    params: *project-ops-params

- name: build-concourse-helm-resource-image
  plan:
  - get: concourse-helm-resource
    trigger: true
  - put: concourse-helm-resource-image
    params:
      build: concourse-helm-resource

- name: deploy-gke
  plan:
  - get: concourse-gcp-tf-bootstrap
    passed: [setup-project]
    trigger: true
  - get: scf-tutorial
    trigger: true
  - put: gke-tf
    params:
      terraform_source: scf-tutorial/ci/tf/gke
      env_name: default

- name: deploy-scf
  plan:
  - get: scf-tutorial
    passed: [deploy-gke]
  - get: gke-tf
    trigger: true
    passed: [deploy-gke]
  - task: extract-kubeconfig
    file: scf-tutorial/ci/tasks/tf-metadata-to-file.yml
    input_mapping:
      terraform: gke-tf
    params:
      METADATA_KEY: kubeconfig_content
      OUTPUT_FILE: kube.config
  - task: test-kubeconfig
    config:
      image_resource:
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
          tag: latest
      inputs:
      - name: tf-metadata-to-file
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          kubectl cluster-info --kubeconfig tf-metadata-to-file/kube.config
  - put: kubernetes
    params:
      kubectl: apply -f scf-tutorial/k8s/tiller-service-account.yaml
      kubeconfig_file: tf-metadata-to-file/kube.config
  - get: scf-release
  - task: test-kubeconfig
    config:
      image_resource:
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
          tag: latest
      inputs:
      - name: scf-release
      outputs:
      - name: scf-release-unzipped
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          unzip scf-release/scf*.zip -d scf-release-unzipped
  - put: helm
    params:
      chart: scf-release-unzipped/helm/uaa/
      release: uaa
      kubeconfig_path: tf-metadata-to-file/kube.config
