---
resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.13

resources:
- name: tfstate
  type: gcs-resource
  source:
    bucket: ((project_id))
    json_key: ((gcp_credentials_json))
    versioned_file: ci/terraform.tfstate
- name: concourse-gcp-tf-bootstrap
  type: git
  source:
    uri: https://github.com/EngineerBetter/concourse-gcp-tf-bootstrap.git
    branch: master
- name: scf-tutorial
  type: git
  source:
    uri: https://github.com/EngineerBetter/scf-tutorial.git
    branch: master
- name: gke-tf
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: ((project_id))
      prefix: gke
      region: ((bucket_location))
      credentials: ((gcp_credentials_json))

jobs:
- name: setup-project
  plan:
  - get: concourse-gcp-tf-bootstrap
    trigger: true
  - task: bootstrap-terraform
    file: concourse-gcp-tf-bootstrap/tasks/bootstrap.yml
    input_mapping:
      gcp-bootstrap: concourse-gcp-tf-bootstrap
    params:
      BILLING_ACCOUNT_ID: ((billing_account_id))
      BUCKET_LOCATION: ((bucket_location))
      FOLDER_NAME: ((folder_name))
      GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
      ORGANIZATION_ID: ((organization_id))
      PROJECT_ID: ((project_id))
      PROJECT_NAME: ((project_name))
  - put: tfstate
    params:
      file: tfstate-out/terraform.tfstate

- name: teardown-project
  plan:
  - get: concourse-gcp-tf-bootstrap
    passed: [setup-project]
  - get: tfstate
    passed: [setup-project]
  - task: bootstrap-terraform
    file: concourse-gcp-tf-bootstrap/tasks/teardown.yml
    input_mapping:
      gcp-bootstrap: concourse-gcp-tf-bootstrap
    params:
      BILLING_ACCOUNT_ID: ((billing_account_id))
      BUCKET_LOCATION: ((bucket_location))
      FOLDER_NAME: ((folder_name))
      GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
      ORGANIZATION_ID: ((organization_id))
      PROJECT_ID: ((project_id))
      PROJECT_NAME: ((project_name))

- name: deploy-gke
  plan:
  - get: scf-tutorial
    trigger: true
  - put: gke-tf
    params:
      terraform_source: scf-tutorial/ci/tf/gke
      env_name: default
