---
resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.13
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
    tag: 2.14.0
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: 1.14

resources:
- name: tfstate
  type: gcs-resource
  source:
    bucket: ((project_id))
    json_key: ((gcp_credentials_json))
    versioned_file: ci/terraform.tfstate
- name: kubeconfig
  type: gcs-resource
  source:
    bucket: ((project_id))
    json_key: ((gcp_credentials_json))
    versioned_file: ci/kube.config
- name: concourse-gcp-tf-bootstrap
  type: git
  source:
    uri: https://github.com/EngineerBetter/concourse-gcp-tf-bootstrap.git
    branch: v1.0.0
- name: scf-tutorial
  type: git
  source:
    <<: &scf-tutorial-source
      uri: https://github.com/EngineerBetter/scf-tutorial.git
      branch: master
    ignore_paths:
    - README.md
    - tutorial.md
- name: scf-tutorial-dockerfile
  type: git
  source:
    <<: *scf-tutorial-source
    paths: [docker/Dockerfile]
- name: scf-tutorial-image
  type: docker-image
  source:
    username: _json_key
    password: ((gcp_credentials_json))
    repository: eu.gcr.io/((project_id))/scf-tutorial
- name: gke-tf
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      prefix: gke
      <<: &tf-backend-config
        bucket: ((project_id))
        region: ((region))
        credentials: ((gcp_credentials_json))
    env:
      GOOGLE_CLOUD_KEYFILE_JSON: ((gcp_credentials_json))
      GOOGLE_PROJECT: ((project_id))
      GOOGLE_REGION: ((region))
      GOOGLE_ZONE: ((zone))
- name: route53-tf
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      prefix: route53
      <<: *tf-backend-config
    env:
      AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
      AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
      AWS_DEFAULT_REGION: us-east-1
- name: helm
  type: helm
  source:
    helm_init_server: true
    helm_init_wait: true
    tiller_service_account: helm
    tracing_enabled: true
    repos:
    - name: minibroker
      url: https://minibroker.blob.core.windows.net/charts
- name: scf-release
  type: github-release
  source:
    owner: SUSE
    repository: scf
- name: kubernetes
  type: kubernetes

jobs:
- name: setup-project
  serial: true
  plan:
  - get: concourse-gcp-tf-bootstrap
  - get: scf-tutorial
    trigger: true
  - task: bootstrap-terraform
    file: concourse-gcp-tf-bootstrap/tasks/bootstrap.yml
    input_mapping: { gcp-bootstrap: concourse-gcp-tf-bootstrap }
    params: &project-ops-params
      BILLING_ACCOUNT_ID: ((billing_account_id))
      BUCKET_LOCATION: ((region))
      FOLDER_NAME: ((folder_name))
      GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
      ORGANIZATION_ID: ((organization_id))
      PROJECT_ID: ((project_id))
      PROJECT_NAME: ((project_name))
  - put: tfstate
    params:
      file: tfstate-out/terraform.tfstate

- name: teardown-project
  serial: true
  plan:
  - get: concourse-gcp-tf-bootstrap
    passed: [setup-project]
  - get: tfstate
    passed: [setup-project]
  - task: bootstrap-terraform
    file: concourse-gcp-tf-bootstrap/tasks/teardown.yml
    input_mapping: { gcp-bootstrap: concourse-gcp-tf-bootstrap }
    params: *project-ops-params

- name: deploy-gke
  serial: true
  plan:
  - get: scf-tutorial
    trigger: true
    passed: [setup-project]
  - put: gke-tf
    params:
      terraform_source: scf-tutorial/ci/tf/gke
      env_name: default

- name: route53
  serial: true
  plan:
  - get: scf-tutorial
    trigger: true
    passed: [deploy-gke]
  - get: gke-tf
    passed: [deploy-gke]
    trigger: true
  - put: route53-tf
    params:
      terraform_source: scf-tutorial/ci/tf/aws-dns
      env_name: default
      var_files:
      - gke-tf/metadata

- name: teardown-route53
  serial: true
  plan:
  - get: scf-tutorial
    passed: [deploy-gke]
  - get: gke-tf
    passed: [deploy-gke]
  - put: route53-tf
    params:
      action: destroy
      terraform_source: scf-tutorial/ci/tf/aws-dns
      env_name: default
      var_files:
      - gke-tf/metadata
    get_params:
      action: destroy

- name: teardown-gke
  serial: true
  plan:
  - get: scf-tutorial
    passed: [teardown-route53]
  - get: gke-tf
    passed: [teardown-route53]
  - put: gke-tf
    params:
      action: destroy
      terraform_source: scf-tutorial/ci/tf/gke
      env_name: default
    get_params:
      action: destroy

- name: extract-kubeconfig
  serial: true
  plan:
  - get: scf-tutorial
    passed: [deploy-gke]
    trigger: true
  - get: gke-tf
    trigger: true
    passed: [deploy-gke]
  - task: extract-kubeconfig
    file: scf-tutorial/ci/tasks/tf-metadata-to-file.yml
    input_mapping: { terraform: gke-tf }
    params:
      METADATA_KEY: kubeconfig_content
      OUTPUT_FILE: kube.config
  - task: test-kubeconfig
    config:
      image_resource: &pcf-ops
        type: docker-image
        source:
          repository: engineerbetter/pcf-ops
          tag: latest
      inputs: [{ name: tf-metadata-to-file }]
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          kubectl cluster-info --kubeconfig tf-metadata-to-file/kube.config
  - put: kubeconfig
    params:
      file: tf-metadata-to-file/kube.config

- name: create-student-sa
  plan:
  - get: scf-tutorial
    passed: [extract-kubeconfig]
    trigger: true
  - get: kubeconfig
    passed: [extract-kubeconfig]
    trigger: true
  - put: kubernetes
    params:
      kubectl: apply -f scf-tutorial/k8s/student/
      kubeconfig_file: kubeconfig/kube.config

- name: build-image
  plan:
  - get: scf-tutorial-dockerfile
    trigger: true
  - get: kubeconfig
    passed: [create-student-sa]
    trigger: true
  - task: write-student-kubeconfig
    config:
      image_resource: *pcf-ops
      inputs: [{ name: kubeconfig }]
      outputs: [{ name: student-kubeconfig }]
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          export KUBECONFIG=kubeconfig/kube.config
          SA_SECRET=$( kubectl get sa -n default student -o jsonpath='{.secrets[0].name}' )

          # Pull the bearer token and cluster CA from the service account secret.
          BEARER_TOKEN=$( kubectl get secrets -n default $SA_SECRET -o jsonpath='{.data.token}' | base64 -d )
          kubectl get secrets -n default $SA_SECRET -o jsonpath='{.data.ca\.crt}' | base64 -d > $TEMPDIR/ca.crt

          CLUSTER_URL=$( kubectl config view -o jsonpath='{.clusters[0].cluster.server}' )

          KUBECONFIG=student-kubeconfig/kube.config

          kubectl config --kubeconfig=$KUBECONFIG \
              set-cluster \
              $CLUSTER_URL \
              --server=$CLUSTER_URL \
              --certificate-authority=$TEMPDIR/ca.crt \
              --embed-certs=true

          kubectl config --kubeconfig=$KUBECONFIG \
              set-credentials student --token=$BEARER_TOKEN

          kubectl config --kubeconfig=$KUBECONFIG \
              set-context registry \
              --cluster=$CLUSTER_URL \
              --user=student

          kubectl config --kubeconfig=$KUBECONFIG \
              use-context registry

          echo "student kubeconfig written to file \"$KUBECONFIG\""
  - task: merge-directories
    config:
      image_resource: *pcf-ops
      inputs:
      - name: scf-tutorial-dockerfile
      - name: student-kubeconfig
      outputs: [{ name: docker-build-dir }]
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          cp scf-tutorial-dockerfile/docker/Dockerfile docker-build-dir/
          cp student-kubeconfig/kube.config docker-build-dir/
  - put: scf-tutorial-image
    params:
      build: docker-build-dir
  - task: make-bucket-public
    config:
      image_resource: *pcf-ops
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          echo '((gcp_credentials_json))' > creds.json
          gcloud auth activate-service-account --key-file creds.json
          gsutil iam ch allUsers:objectViewer gs://((project_id))

- name: deploy-scf
  serial: true
  plan:
  - get: scf-tutorial
    passed: [extract-kubeconfig]
    trigger: true
  - get: kubeconfig
    passed: [extract-kubeconfig]
    trigger: true
  - put: kubernetes
    params:
      kubectl: apply -f scf-tutorial/k8s/scf
      kubeconfig_file: kubeconfig/kube.config
  - get: scf-release
  - task: unzip-scf-release
    config:
      image_resource: *pcf-ops
      inputs: [{ name: scf-release }]
      outputs: [{ name: scf-release-unzipped }]
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          unzip scf-release/scf*.zip -d scf-release-unzipped
  - get: gke-tf
    passed: [deploy-gke]
  - task: extract-uaa-ip
    file: scf-tutorial/ci/tasks/tf-metadata-to-file.yml
    input_mapping: { terraform: gke-tf }
    output_mapping: { tf-metadata-to-file: uaa_ip }
    params:
      METADATA_KEY: uaa_ip
      OUTPUT_FILE: uaa_ip
  - put: helm
    params:
      chart: scf-tutorial/scf/helm/uaa/
      release: uaa
      namespace: uaa
      values: scf-tutorial/scf/scf-config-values.yaml
      override_values:
      - key: kube.storage_class.persistent
        value: standard
      - key: services.loadbalanced
        value: true
      - key: services.uaa_load_balancer_ip
        path: uaa_ip/uaa_ip
      - key: env.DOMAIN
        value: scf.engineerbetter.com
      wait_until_ready: 480
      kubeconfig_path: kubeconfig/kube.config
  - task: write-ca-cert
    config:
      image_resource: *pcf-ops
      inputs:
      - name: scf-release-unzipped
      - name: kubeconfig
      outputs: [{ name: ca_cert }]
      platform: linux
      run:
        path: bash
        args:
        - -exc
        - |
          export KUBECONFIG=kubeconfig/kube.config
          kubectl cluster-info
          kubectl get pods --namespace uaa -o jsonpath='{.items[?(.metadata.name=="uaa-0")].spec.containers[?(.name=="uaa")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretKeyRef.name}'
          SECRET=$(kubectl get pods --namespace uaa -o jsonpath='{.items[?(.metadata.name=="uaa-0")].spec.containers[?(.name=="uaa")].env[?(.name=="INTERNAL_CA_CERT")].valueFrom.secretKeyRef.name}')
          kubectl get secret $SECRET --namespace uaa -o jsonpath="{.data['internal-ca-cert']}" | base64 --decode - > ca_cert/ca_cert
          cat ca_cert/ca_cert
  - task: extract-ssh-ip
    file: scf-tutorial/ci/tasks/tf-metadata-to-file.yml
    input_mapping: { terraform: gke-tf }
    output_mapping: { tf-metadata-to-file: ssh_ip }
    params:
      METADATA_KEY: ssh_ip
      OUTPUT_FILE: ssh_ip
  - task: extract-router-ip
    file: scf-tutorial/ci/tasks/tf-metadata-to-file.yml
    input_mapping: { terraform: gke-tf }
    output_mapping: { tf-metadata-to-file: router_ip }
    params:
      METADATA_KEY: router_ip
      OUTPUT_FILE: router_ip
  - put: helm
    params:
      chart: scf-tutorial/scf/helm/cf/
      release: cf
      namespace: cf
      values: scf-tutorial/scf/scf-config-values.yaml
      override_values:
      - key: secrets.UAA_CA_CERT
        path: ca_cert/ca_cert
      - key: env.DOMAIN
        value: scf.engineerbetter.com
      - key: env.UAA_HOST
        value: uaa.scf.engineerbetter.com
      - key: env.UAA_PORT
        value: 2793
      - key: services.loadbalanced
        value: true
      - key: services.ssh_load_balancer_ip
        path: ssh_ip/ssh_ip
      - key: services.router_load_balancer_ip
        path: router_ip/router_ip
      wait_until_ready: 900
      kubeconfig_path: kubeconfig/kube.config

- name: deploy-minibroker
  plan:
  - get: scf-tutorial
    passed: [deploy-scf]
    trigger: true
  - get: kubeconfig
    passed: [extract-kubeconfig]
    trigger: true
  - put: helm
    params:
      chart: minibroker/minibroker
      release: minibroker
      namespace: minibroker
      override_values:
      - key: deployServiceCatalog
        value: "false"
      - key: defaultNamespace
        value: minibroker
      wait_until_ready: 900
      kubeconfig_path: kubeconfig/kube.config
