---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "adapter-set"
    labels:
      app.kubernetes.io/component: "adapter-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "adapter"
      port: 4443
      protocol: "TCP"
      targetPort: 0
    - name: "adapter-health"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "adapter"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "adapter-adapter-set"
    labels:
      app.kubernetes.io/component: "adapter-adapter-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "adapter"
      port: 4443
      protocol: "TCP"
      targetPort: 0
    - name: "adapter-health"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "adapter"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "adapter-adapter"
    labels:
      app.kubernetes.io/component: "adapter-adapter"
  spec:
    ports:
    - name: "adapter"
      port: 4443
      protocol: "TCP"
      targetPort: 4443
    - name: "adapter-health"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app.kubernetes.io/component: "adapter"
kind: "List"
---
# The adapter instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: adapter and bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "adapter"
  labels:
    app.kubernetes.io/component: "adapter"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "adapter"
  serviceName: "adapter-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "adapter"
      name: "adapter"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "SYSLOG_ADAPT_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-adapt-cert"
              name: "secrets"
        - name: "SYSLOG_ADAPT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-adapt-cert-key"
              name: "secrets"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-adapter:f25874908e197430f3cb3f2717dba2c4db5f0ce0"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "adapter"
        ports:
        - containerPort: 4443
          name: "adapter"
          protocol: "TCP"
        - containerPort: 8080
          name: "adapter-health"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8080/health"
        resources:
          requests:
            memory: "128Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "default-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
