---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-metrics-set"
    labels:
      app.kubernetes.io/component: "autoscaler-metrics-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "metrics"
      port: 7103
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-metrics"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-metrics-metricscollector-set"
    labels:
      app.kubernetes.io/component: "autoscaler-metrics-metricscollector-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "metrics"
      port: 7103
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-metrics"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-metrics-metricscollector"
    labels:
      app.kubernetes.io/component: "autoscaler-metrics-metricscollector"
  spec:
    ports:
    - name: "metrics"
      port: 7103
      protocol: "TCP"
      targetPort: 7103
    selector:
      app.kubernetes.io/component: "autoscaler-metrics"
kind: "List"
---
# The autoscaler-metrics instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: metricscollector
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-metrics"
  labels:
    app.kubernetes.io/component: "autoscaler-metrics"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "autoscaler-metrics"
  serviceName: "autoscaler-metrics-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "autoscaler-metrics"
      name: "autoscaler-metrics"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_ASMETRICS_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-server-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_INSTANCE_METRICS_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECTOR_COLLECT_INTERVAL"
          value: "30s"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECTOR_REFRESH_INTERVAL"
          value: "60s"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECTOR_SAVE_INTERVAL"
          value: "30s"
        - name: "AUTOSCALER_METRICS_COLLECTOR_COLLECT_METHOD"
          value: "streaming"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_UAA_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-uaa-client-secret"
              name: "secrets"
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-autoscaler-metrics:697cfa643d01d0a97a0822e5d769f7e888523657"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-metrics"
        ports:
        - containerPort: 7103
          name: "metrics"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "128Mi"
            cpu: "4000m"
          limits: {}
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
