---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-eventgenerator-set"
    labels:
      app.kubernetes.io/component: "autoscaler-eventgenerator-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "eventgen"
      port: 7105
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-eventgenerator"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-eventgenerator-eventgenerator-set"
    labels:
      app.kubernetes.io/component: "autoscaler-eventgenerator-eventgenerator-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "eventgen"
      port: 7105
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-eventgenerator"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-eventgenerator-eventgenerator"
    labels:
      app.kubernetes.io/component: "autoscaler-eventgenerator-eventgenerator"
  spec:
    ports:
    - name: "eventgen"
      port: 7105
      protocol: "TCP"
      targetPort: 7105
    selector:
      app.kubernetes.io/component: "autoscaler-eventgenerator"
kind: "List"
---
# The autoscaler-eventgenerator instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: eventgenerator
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-eventgenerator"
  labels:
    app.kubernetes.io/component: "autoscaler-eventgenerator"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "autoscaler-eventgenerator"
  serviceName: "autoscaler-eventgenerator-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "autoscaler-eventgenerator"
      name: "autoscaler-eventgenerator"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_APPMETRICS_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-server-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "AUTOSCALER_DEFAULT_BREACH_DURATION_SECS"
          value: "300"
        - name: "AUTOSCALER_DEFAULT_STAT_WINDOW_SECS"
          value: "300"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_APP_METRIC_CHANNEL_SIZE"
          value: "1000"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_APP_MONITOR_CHANNEL_SIZE"
          value: "200"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_EXECUTE_INTERVAL"
          value: "40s"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_METRIC_POLLER_COUNT"
          value: "20"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_POLICY_POLLER_INTERVAL"
          value: "40s"
        - name: "AUTOSCALER_EVENT_GENERATOR_AGGREGATOR_SAVE_INTERVAL"
          value: "5s"
        - name: "AUTOSCALER_EVENT_GENERATOR_CIRCUIT_BREAKER_BACK_OFF_INITIAL_INTERVAL"
          value: "5m"
        - name: "AUTOSCALER_EVENT_GENERATOR_CIRCUIT_BREAKER_BACK_OFF_MAX_INTERVAL"
          value: "120m"
        - name: "AUTOSCALER_EVENT_GENERATOR_CIRCUIT_BREAKER_CONSECUTIVE_FAILURE_COUNT"
          value: "3"
        - name: "AUTOSCALER_EVENT_GENERATOR_EVALUATOR_EVALUATION_MANAGER_EXECUTE_INTERVAL"
          value: "40s"
        - name: "AUTOSCALER_EVENT_GENERATOR_EVALUATOR_EVALUATOR_COUNT"
          value: "20"
        - name: "AUTOSCALER_EVENT_GENERATOR_EVALUATOR_TRIGGER_ARRAY_CHANNEL_SIZE"
          value: "200"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_CONNECTION_MAX_LIFETIME"
          value: "60s"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_IDLE_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_POLICY_DB_CONNECTION_CONFIG_MAX_OPEN_CONNECTIONS"
          value: "100"
        - name: "AUTOSCALER_SCALING_ENGINE_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-scaling-engine-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_SCALING_ENGINE_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-scaling-engine-client-cert-key"
              name: "secrets"
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-autoscaler-eventgenerator:965179a4f8a0240ab04479f0f1184ff204136415"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-eventgenerator"
        ports:
        - containerPort: 7105
          name: "eventgen"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "2350Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
