---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres-set"
    labels:
      app.kubernetes.io/component: "autoscaler-postgres-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-postgres"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres-postgres-set"
    labels:
      app.kubernetes.io/component: "autoscaler-postgres-postgres-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-postgres"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-postgres-postgres"
    labels:
      app.kubernetes.io/component: "autoscaler-postgres-postgres"
  spec:
    ports:
    - name: "postgres"
      port: 5432
      protocol: "TCP"
      targetPort: 5432
    selector:
      app.kubernetes.io/component: "autoscaler-postgres"
kind: "List"
---
# The autoscaler-postgres instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - postgres: The Postgres server provides a single instance Postgres database
#   that can be used with the Cloud Controller or the UAA. It does not provide
#   highly-available configuration.
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-postgres"
  labels:
    app.kubernetes.io/component: "autoscaler-postgres"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "autoscaler-postgres"
  serviceName: "autoscaler-postgres-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "autoscaler-postgres"
      name: "autoscaler-postgres"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_DATABASE_MAX_CONNECTIONS"
          value: "1000"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-autoscaler-postgres:239ae598e2189ea7bc3ab8aac91cd31689879070"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-postgres"
        ports:
        - containerPort: 5432
          name: "postgres"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "1024Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: "/var/vcap/store"
          name: "postgres-data"
          readOnly: false
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
  volumeClaimTemplates:
  - metadata:
      name: "postgres-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: "persistent"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "5G"
