---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-api-set"
    labels:
      app.kubernetes.io/component: "autoscaler-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "api"
      port: 7100
      protocol: "TCP"
      targetPort: 0
    - name: "api-public"
      port: 7106
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-api-apiserver-set"
    labels:
      app.kubernetes.io/component: "autoscaler-api-apiserver-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "api"
      port: 7100
      protocol: "TCP"
      targetPort: 0
    - name: "api-public"
      port: 7106
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "autoscaler-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "autoscaler-api-apiserver"
    labels:
      app.kubernetes.io/component: "autoscaler-api-apiserver"
  spec:
    ports:
    - name: "api"
      port: 7100
      protocol: "TCP"
      targetPort: 7100
    - name: "api-public"
      port: 7106
      protocol: "TCP"
      targetPort: 7106
    selector:
      app.kubernetes.io/component: "autoscaler-api"
kind: "List"
---
# The autoscaler-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - route_registrar: Used for registering routes
#
# Also: apiserver and bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "autoscaler-api"
  labels:
    app.kubernetes.io/component: "autoscaler-api"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "autoscaler-api"
  serviceName: "autoscaler-api-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "autoscaler-api"
      name: "autoscaler-api"
    spec:
      containers:
      - env:
        - name: "AUTOSCALER_API_SERVER_CACHE_TTL"
          value: "600"
        - name: "AUTOSCALER_API_SERVER_DB_CONFIG_IDLE_TIMEOUT"
          value: "100"
        - name: "AUTOSCALER_API_SERVER_DB_CONFIG_MAX_CONNECTIONS"
          value: "10"
        - name: "AUTOSCALER_API_SERVER_DB_CONFIG_MIN_CONNECTIONS"
          value: "0"
        - name: "AUTOSCALER_API_SERVER_INFO_BUILD"
          value: "beta"
        - name: "AUTOSCALER_API_SERVER_INFO_DESCRIPTION"
          value: "autoscaler"
        - name: "AUTOSCALER_API_SERVER_INFO_NAME"
          value: "autoscalerapiserver"
        - name: "AUTOSCALER_API_SERVER_INFO_SUPPORT_URL"
          value: ""
        - name: "AUTOSCALER_ASAPI_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-client-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_PUBLIC_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-public-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_PUBLIC_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-public-server-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-server-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASAPI_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asapi-server-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_ASMETRICS_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-asmetrics-client-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-db-password"
              name: "secrets"
        - name: "AUTOSCALER_SCALING_ENGINE_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-scaling-engine-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_SCALING_ENGINE_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-scaling-engine-client-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_SCHEDULER_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-scheduler-client-cert"
              name: "secrets"
        - name: "AUTOSCALER_SCHEDULER_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "autoscaler-scheduler-client-cert-key"
              name: "secrets"
        - name: "AUTOSCALER_SERVICE_OFFERING_ENABLED"
          value: "false"
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "DOMAIN"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-autoscaler-api:55643559dd5eeb5fdd766c197c223636003e4fa6"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "autoscaler-api"
        ports:
        - containerPort: 7100
          name: "api"
          protocol: "TCP"
        - containerPort: 7106
          name: "api-public"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "256Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "default-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
