---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "bits-set"
    labels:
      app.kubernetes.io/component: "bits-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "server"
      port: 443
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "bits"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "bits-bits-service-set"
    labels:
      app.kubernetes.io/component: "bits-bits-service-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "server"
      port: 443
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "bits"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "bits-bits-service"
    labels:
      app.kubernetes.io/component: "bits-bits-service"
  spec:
    ports:
    - name: "server"
      port: 443
      protocol: "TCP"
      targetPort: 443
    selector:
      app.kubernetes.io/component: "bits"
kind: "List"
---
# The bits instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - route_registrar: Used for registering routes
#
# - eirinifs: This job copies the eirinifs to a desired location
#
# Also: statsd_injector, bpm, and bits-service
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "bits"
  labels:
    app.kubernetes.io/component: "bits"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "bits"
  serviceName: "bits-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "bits"
      name: "bits"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "BITS_ADMIN_USERS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "bits-admin-users-password"
              name: "secrets"
        - name: "BITS_SERVICE_SECRET"
          valueFrom:
            secretKeyRef:
              key: "bits-service-secret"
              name: "secrets"
        - name: "BITS_SERVICE_SSL_CERT"
          valueFrom:
            secretKeyRef:
              key: "bits-service-ssl-cert"
              name: "secrets"
        - name: "BITS_SERVICE_SSL_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bits-service-ssl-cert-key"
              name: "secrets"
        - name: "BLOBSTORE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "blobstore-password"
              name: "secrets"
        - name: "CATS_SUITES"
          value: ""
        - name: "CC_PUBLIC_TLS_CERT"
          valueFrom:
            secretKeyRef:
              key: "cc-public-tls-cert"
              name: "secrets"
        - name: "CC_PUBLIC_TLS_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "cc-public-tls-cert-key"
              name: "secrets"
        - name: "CC_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "cc-server-crt"
              name: "secrets"
        - name: "CC_SERVER_CRT_KEY"
          valueFrom:
            secretKeyRef:
              key: "cc-server-crt-key"
              name: "secrets"
        - name: "DOMAIN"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-bits:7c1d65845a089e7cec55a05c8b7358df373b02d5"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "bits"
        ports:
        - containerPort: 443
          name: "server"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "256Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "default-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
