---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "blobstore-set"
    labels:
      app.kubernetes.io/component: "blobstore-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "blobstore-ext"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    - name: "blobstore"
      port: 4443
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "blobstore"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "blobstore-blobstore-set"
    labels:
      app.kubernetes.io/component: "blobstore-blobstore-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "blobstore-ext"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    - name: "blobstore"
      port: 4443
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "blobstore"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "blobstore-blobstore"
    labels:
      app.kubernetes.io/component: "blobstore-blobstore"
  spec:
    ports:
    - name: "blobstore-ext"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    - name: "blobstore"
      port: 4443
      protocol: "TCP"
      targetPort: 4443
    selector:
      app.kubernetes.io/component: "blobstore"
kind: "List"
---
# The blobstore instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - route_registrar: Used for registering routes
#
# Also: blobstore and bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "blobstore"
  labels:
    app.kubernetes.io/component: "blobstore"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "blobstore"
  serviceName: "blobstore-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "blobstore"
      name: "blobstore"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "BLOBSTORE_ACCESS_RULES"
          value: "allow 10.0.0.0/8; allow 172.16.0.0/12; allow 192.168.0.0/16;"
        - name: "BLOBSTORE_MAX_UPLOAD_SIZE"
          value: "5000"
        - name: "BLOBSTORE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "blobstore-password"
              name: "secrets"
        - name: "BLOBSTORE_SECURE_LINK"
          valueFrom:
            secretKeyRef:
              key: "blobstore-secure-link"
              name: "secrets"
        - name: "BLOBSTORE_TLS_CERT"
          valueFrom:
            secretKeyRef:
              key: "blobstore-tls-cert"
              name: "secrets"
        - name: "BLOBSTORE_TLS_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "blobstore-tls-cert-key"
              name: "secrets"
        - name: "CATS_SUITES"
          value: ""
        - name: "DOMAIN"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-blobstore:a1072ad6f00178c763bb31b76410e6b8c91e5bec"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "blobstore"
        ports:
        - containerPort: 8080
          name: "blobstore-ext"
          protocol: "TCP"
        - containerPort: 4443
          name: "blobstore"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "500Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/vcap/store"
          name: "blobstore-data"
          readOnly: false
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "default-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
  volumeClaimTemplates:
  - metadata:
      name: "blobstore-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: "persistent"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "50G"
