---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb-group-set"
    labels:
      app.kubernetes.io/component: "cf-usb-group-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: 0
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "cf-usb-group"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb-set"
    labels:
      app.kubernetes.io/component: "cf-usb-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: 0
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "cf-usb-group"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb"
    labels:
      app.kubernetes.io/component: "cf-usb"
  spec:
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: 24054
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: 24053
    selector:
      app.kubernetes.io/component: "cf-usb-group"
kind: "List"
---
# The cf-usb-group instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: cf-usb and bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "cf-usb-group"
  labels:
    app.kubernetes.io/component: "cf-usb-group"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "cf-usb-group"
  serviceName: "cf-usb-group-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "cf-usb-group"
      name: "cf-usb-group"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "CF_USB_BROKER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert"
              name: "secrets"
        - name: "CF_USB_BROKER_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert-key"
              name: "secrets"
        - name: "CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-password"
              name: "secrets"
        - name: "DOMAIN"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-cf-usb-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_CF_USB_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cf-usb-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: ""
        - name: "UAA_PORT"
          value: "2793"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-cf-usb-group:f4ff0a7d6d598396de17e0d6681511fa2c1b4995"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "cf-usb-group"
        ports:
        - containerPort: 24054
          name: "usb"
          protocol: "TCP"
        - containerPort: 24053
          name: "usb2"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "128Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "default-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
