---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "credhub-user-set"
    labels:
      app.kubernetes.io/component: "credhub-user-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "api"
      port: 8844
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "credhub-user"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "credhub-user-credhub-set"
    labels:
      app.kubernetes.io/component: "credhub-user-credhub-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "api"
      port: 8844
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "credhub-user"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "credhub-user-credhub"
    labels:
      app.kubernetes.io/component: "credhub-user-credhub"
  spec:
    ports:
    - name: "api"
      port: 8844
      protocol: "TCP"
      targetPort: 8844
    selector:
      app.kubernetes.io/component: "credhub-user"
kind: "List"
---
# The credhub-user instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - route_registrar: Used for registering routes
#
# Also: credhub and bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "credhub-user"
  labels:
    app.kubernetes.io/component: "credhub-user"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "credhub-user"
  serviceName: "credhub-user-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "credhub-user"
      name: "credhub-user"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "CREDHUB_ENCRYPT_KEY"
          valueFrom:
            secretKeyRef:
              key: "credhub-encrypt-key"
              name: "secrets"
        - name: "CREDHUB_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "credhub-server-cert"
              name: "secrets"
        - name: "CREDHUB_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "credhub-server-cert-key"
              name: "secrets"
        - name: "DOMAIN"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_CREDHUB_USER_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-credhub-user-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_HOST"
          value: ""
        - name: "UAA_PORT"
          value: "2793"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-credhub-user:23753493c2c46f7d6e0e3233147914a5877bb577"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "credhub-user"
        ports:
        - containerPort: 8844
          name: "api"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "2000Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "default-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
