---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-brain-set"
    labels:
      app.kubernetes.io/component: "diego-brain-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "diego-auction"
      port: 9016
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "diego-brain"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-brain-auctioneer-set"
    labels:
      app.kubernetes.io/component: "diego-brain-auctioneer-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "diego-auction"
      port: 9016
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "diego-brain"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-brain-auctioneer"
    labels:
      app.kubernetes.io/component: "diego-brain-auctioneer"
  spec:
    ports:
    - name: "diego-auction"
      port: 9016
      protocol: "TCP"
      targetPort: 9016
    selector:
      app.kubernetes.io/component: "diego-brain"
      skiff-role-active: "true"
kind: "List"
---
# The diego-brain instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   SCF patches for upstream bugs
#
# Also: auctioneer and cfdot
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "diego-brain"
  labels:
    app.kubernetes.io/component: "diego-brain"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "diego-brain"
  serviceName: "diego-brain-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "diego-brain"
      name: "diego-brain"
    spec:
      containers:
      - env:
        - name: "AUCTIONEER_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-rep-cert"
              name: "secrets"
        - name: "AUCTIONEER_REP_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-rep-cert-key"
              name: "secrets"
        - name: "AUCTIONEER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-server-cert"
              name: "secrets"
        - name: "AUCTIONEER_SERVER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-server-cert-key"
              name: "secrets"
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets"
        - name: "BBS_CLIENT_CRT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt-key"
              name: "secrets"
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets"
        - name: "BBS_REP_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert-key"
              name: "secrets"
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-diego-brain:52cec78ce1399d1236e8fbf3d5f2d64ee1c87aed"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-brain"
        ports:
        - containerPort: 9016
          name: "diego-auction"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/usr/bin/env"
            - "FISSILE_ACTIVE_PASSIVE_PROBE=head -c0 </dev/tcp/${HOSTNAME}/9016"
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "128Mi"
            cpu: "4000m"
          limits: {}
        securityContext:
          capabilities:
            add:
            - "SYS_RESOURCE"
          allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
