---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-ssh-set"
    labels:
      app.kubernetes.io/component: "diego-ssh-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "diego-ssh"
      port: 2222
      protocol: "TCP"
      targetPort: 0
    - name: "diego-files"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "diego-ssh"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-ssh-ssh-proxy-set"
    labels:
      app.kubernetes.io/component: "diego-ssh-ssh-proxy-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "diego-ssh"
      port: 2222
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "diego-ssh"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-ssh-ssh-proxy"
    labels:
      app.kubernetes.io/component: "diego-ssh-ssh-proxy"
  spec:
    ports:
    - name: "diego-ssh"
      port: 2222
      protocol: "TCP"
      targetPort: 2222
    selector:
      app.kubernetes.io/component: "diego-ssh"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-ssh-ssh-proxy-public"
    labels:
      app.kubernetes.io/component: "diego-ssh-ssh-proxy-public"
  spec:
    externalIPs:
    - "192.168.77.77"
    ports:
    - name: "diego-ssh"
      port: 2222
      protocol: "TCP"
      targetPort: 2222
    selector:
      app.kubernetes.io/component: "diego-ssh"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-access-set"
    labels:
      app.kubernetes.io/component: "diego-access-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "diego-files"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "diego-ssh"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-access"
    labels:
      app.kubernetes.io/component: "diego-access"
  spec:
    ports:
    - name: "diego-files"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app.kubernetes.io/component: "diego-ssh"
kind: "List"
---
# The diego-ssh instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: ssh_proxy and file_server
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "diego-ssh"
  labels:
    app.kubernetes.io/component: "diego-ssh"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "diego-ssh"
  serviceName: "diego-ssh-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "diego-ssh"
      name: "diego-ssh"
    spec:
      containers:
      - env:
        - name: "APP_SSH_KEY"
          valueFrom:
            secretKeyRef:
              key: "app-ssh-key"
              name: "secrets"
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets"
        - name: "BBS_CLIENT_CRT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt-key"
              name: "secrets"
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_DIEGO_SSH_PROXY_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-diego-ssh-proxy-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: ""
        - name: "UAA_PORT"
          value: "2793"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-diego-ssh:b86615560ae08b54979dacd0e2562386f5e14602"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-ssh"
        ports:
        - containerPort: 2222
          name: "diego-ssh"
          protocol: "TCP"
        - containerPort: 8080
          name: "diego-files"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8080/v1/static/file_server/bin/file-server"
        resources:
          requests:
            memory: "128Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          capabilities:
            add:
            - "SYS_RESOURCE"
          allowPrivilegeEscalation: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
