---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "doppler-set"
    labels:
      app.kubernetes.io/component: "doppler-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "log-cache"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    - name: "dropsonde-udp"
      port: 3457
      protocol: "UDP"
      targetPort: 0
    - name: "dropsonde-tcp"
      port: 3458
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-tls"
      port: 3459
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-ws"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-grpc"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    - name: "log-cache-proxy"
      port: 8083
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "doppler"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "doppler-log-cache-set"
    labels:
      app.kubernetes.io/component: "doppler-log-cache-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "log-cache"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "doppler"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "doppler-log-cache"
    labels:
      app.kubernetes.io/component: "doppler-log-cache"
  spec:
    ports:
    - name: "log-cache"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    selector:
      app.kubernetes.io/component: "doppler"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "doppler-doppler-set"
    labels:
      app.kubernetes.io/component: "doppler-doppler-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "dropsonde-udp"
      port: 3457
      protocol: "UDP"
      targetPort: 0
    - name: "dropsonde-tcp"
      port: 3458
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-tls"
      port: 3459
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-ws"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-grpc"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    - name: "log-cache-proxy"
      port: 8083
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "doppler"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "doppler-doppler"
    labels:
      app.kubernetes.io/component: "doppler-doppler"
  spec:
    ports:
    - name: "dropsonde-udp"
      port: 3457
      protocol: "UDP"
      targetPort: 3457
    - name: "dropsonde-tcp"
      port: 3458
      protocol: "TCP"
      targetPort: 3458
    - name: "doppler-tls"
      port: 3459
      protocol: "TCP"
      targetPort: 3459
    - name: "doppler-ws"
      port: 8081
      protocol: "TCP"
      targetPort: 8081
    - name: "doppler-grpc"
      port: 8082
      protocol: "TCP"
      targetPort: 8082
    - name: "log-cache-proxy"
      port: 8083
      protocol: "TCP"
      targetPort: 8083
    selector:
      app.kubernetes.io/component: "doppler"
kind: "List"
---
# The doppler instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: log-cache-gateway, log-cache-nozzle, log-cache-cf-auth-proxy,
# log-cache-expvar-forwarder, log-cache, doppler, and bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "doppler"
  labels:
    app.kubernetes.io/component: "doppler"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "doppler"
  serviceName: "doppler-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "doppler"
      name: "doppler"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "DOMAIN"
          value: ""
        - name: "DOPPLER_CERT"
          valueFrom:
            secretKeyRef:
              key: "doppler-cert"
              name: "secrets"
        - name: "DOPPLER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "doppler-cert-key"
              name: "secrets"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "LOG_CACHE_CERT"
          valueFrom:
            secretKeyRef:
              key: "log-cache-cert"
              name: "secrets"
        - name: "LOG_CACHE_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "log-cache-cert-key"
              name: "secrets"
        - name: "LOG_CACHE_TO_LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "log-cache-to-loggregator-agent-cert"
              name: "secrets"
        - name: "LOG_CACHE_TO_LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "log-cache-to-loggregator-agent-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_DOPPLER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-doppler-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: ""
        - name: "UAA_PORT"
          value: "2793"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-doppler:7d44bbbee1a275c9b9223e6c2ffe0991d029f327"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "doppler"
        ports:
        - containerPort: 8080
          name: "log-cache"
          protocol: "TCP"
        - containerPort: 3457
          name: "dropsonde-udp"
          protocol: "UDP"
        - containerPort: 3458
          name: "dropsonde-tcp"
          protocol: "TCP"
        - containerPort: 3459
          name: "doppler-tls"
          protocol: "TCP"
        - containerPort: 8081
          name: "doppler-ws"
          protocol: "TCP"
        - containerPort: 8082
          name: "doppler-grpc"
          protocol: "TCP"
        - containerPort: 8083
          name: "log-cache-proxy"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "head -c0 </dev/tcp/${HOSTNAME}/8082"
        resources:
          requests:
            memory: "410Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
