---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-set"
    labels:
      app.kubernetes.io/component: "log-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-loggregator-trafficcontroller-set"
    labels:
      app.kubernetes.io/component: "log-api-loggregator-trafficcontroller-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-loggregator-trafficcontroller"
    labels:
      app.kubernetes.io/component: "log-api-loggregator-trafficcontroller"
  spec:
    ports:
    - name: "dropsonde"
      port: 8081
      protocol: "TCP"
      targetPort: 8081
    selector:
      app.kubernetes.io/component: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-reverse-log-proxy-set"
    labels:
      app.kubernetes.io/component: "log-api-reverse-log-proxy-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "log-api"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "log-api-reverse-log-proxy"
    labels:
      app.kubernetes.io/component: "log-api-reverse-log-proxy"
  spec:
    ports:
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: 8082
    selector:
      app.kubernetes.io/component: "log-api"
kind: "List"
---
# The log-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: loggregator_trafficcontroller, reverse_log_proxy, and bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "log-api"
  labels:
    app.kubernetes.io/component: "log-api"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "log-api"
  serviceName: "log-api-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "log-api"
      name: "log-api"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "DOMAIN"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secrets"
        - name: "SYSLOG_RLP_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert-key"
              name: "secrets"
        - name: "TRAFFICCONTROLLER_CERT"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-cert"
              name: "secrets"
        - name: "TRAFFICCONTROLLER_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "trafficcontroller-cert-key"
              name: "secrets"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_DOPPLER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-doppler-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: ""
        - name: "UAA_PORT"
          value: "2793"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-log-api:3d6443cb1df4a0adc0a3a6a7ecf1b55434b6be4b"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "log-api"
        ports:
        - containerPort: 8081
          name: "dropsonde"
          protocol: "TCP"
        - containerPort: 8082
          name: "rlp"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8081/set-cookie"
        resources:
          requests:
            memory: "128Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "default-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
