---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "nfs-broker-set"
    labels:
      app.kubernetes.io/component: "nfs-broker-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "nfsbroker"
      port: 8999
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "nfs-broker"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "nfs-broker-nfsbroker-set"
    labels:
      app.kubernetes.io/component: "nfs-broker-nfsbroker-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "nfsbroker"
      port: 8999
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "nfs-broker"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "nfs-broker-nfsbroker"
    labels:
      app.kubernetes.io/component: "nfs-broker-nfsbroker"
  spec:
    ports:
    - name: "nfsbroker"
      port: 8999
      protocol: "TCP"
      targetPort: 8999
    selector:
      app.kubernetes.io/component: "nfs-broker"
kind: "List"
---
# The nfs-broker instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: nfsbroker
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "nfs-broker"
  labels:
    app.kubernetes.io/component: "nfs-broker"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "nfs-broker"
  serviceName: "nfs-broker-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "nfs-broker"
      name: "nfs-broker"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_PERSI_NFS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-persi-nfs-password"
              name: "secrets"
        - name: "PERSI_NFS_ALLOWED_OPTIONS"
          value: "uid,gid,auto_cache,username,password"
        - name: "PERSI_NFS_BROKER_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "persi-nfs-broker-password"
              name: "secrets"
        - name: "PERSI_NFS_DEFAULT_OPTIONS"
          value: ""
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-nfs-broker:41300e47fe747f648fb0ca44bf97b072baaa4e6c"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "nfs-broker"
        ports:
        - containerPort: 8999
          name: "nfsbroker"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "128Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
