---
# Service account "withsysresource-privileged" is used by the following instance
# groups:
# - routing-api
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "withsysresource-privileged"
  labels:
    app.kubernetes.io/component: "withsysresource-privileged"
---
# Role binding for service account "withsysresource-privileged" and role
# "configgin-role"
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "withsysresource-privileged-configgin-role-binding"
  labels:
    app.kubernetes.io/component: "withsysresource-privileged-configgin-role-binding"
subjects:
- kind: "ServiceAccount"
  name: "withsysresource-privileged"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "configgin-role"
---
# Cluster role binding for service account "withsysresource-privileged" and
# cluster role "withsysresource"
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "withsysresource-privileged-withsysresource-cluster-binding"
  labels:
    app.kubernetes.io/component: "withsysresource-privileged-withsysresource-cluster-binding"
subjects:
- kind: "ServiceAccount"
  name: "withsysresource-privileged"
  namespace: "~"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "withsysresource"
---
# Cluster role binding for service account "withsysresource-privileged" and
# cluster role "privileged"
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "withsysresource-privileged-privileged-cluster-binding"
  labels:
    app.kubernetes.io/component: "withsysresource-privileged-privileged-cluster-binding"
subjects:
- kind: "ServiceAccount"
  name: "withsysresource-privileged"
  namespace: "~"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "privileged"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "routing-api-set"
    labels:
      app.kubernetes.io/component: "routing-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "routing-api"
      port: 3000
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "routing-api"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "routing-api-routing-api-set"
    labels:
      app.kubernetes.io/component: "routing-api-routing-api-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "routing-api"
      port: 3000
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "routing-api"
      skiff-role-active: "true"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "routing-api-routing-api"
    labels:
      app.kubernetes.io/component: "routing-api-routing-api"
  spec:
    ports:
    - name: "routing-api"
      port: 3000
      protocol: "TCP"
      targetPort: 3000
    selector:
      app.kubernetes.io/component: "routing-api"
      skiff-role-active: "true"
kind: "List"
---
# The routing-api instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: bpm and routing-api
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "routing-api"
  labels:
    app.kubernetes.io/component: "routing-api"
spec:
  podManagementPolicy: "OrderedReady"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "routing-api"
  serviceName: "routing-api-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "routing-api"
      name: "routing-api"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets"
        - name: "DIEGO_CLIENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert-key"
              name: "secrets"
        - name: "DOMAIN"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_TCP_ROUTER_PORTS_TCP_ROUTE_MAX"
          value: "20008"
        - name: "KUBE_SIZING_TCP_ROUTER_PORTS_TCP_ROUTE_MIN"
          value: "20000"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_ROUTING_API_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-routing-api-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_HOST"
          value: ""
        - name: "UAA_PORT"
          value: "2793"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-routing-api:049e486e9c249bd792cd8549237dd9544a36c336"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "routing-api"
        ports:
        - containerPort: 3000
          name: "routing-api"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/usr/bin/env"
            - "FISSILE_ACTIVE_PASSIVE_PROBE=head -c0 </dev/tcp/${HOSTNAME}/3000"
            - "/opt/fissile/readiness-probe.sh"
        resources:
          requests:
            memory: "128Mi"
            cpu: "4000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "withsysresource-privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
