---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "router-set"
    labels:
      app.kubernetes.io/component: "router-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "router"
      port: 80
      protocol: "TCP"
      targetPort: 0
    - name: "router-ssl"
      port: 443
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "router"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "router-gorouter-set"
    labels:
      app.kubernetes.io/component: "router-gorouter-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "router"
      port: 80
      protocol: "TCP"
      targetPort: 0
    - name: "router-ssl"
      port: 443
      protocol: "TCP"
      targetPort: 0
    selector:
      app.kubernetes.io/component: "router"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "router-gorouter"
    labels:
      app.kubernetes.io/component: "router-gorouter"
  spec:
    ports:
    - name: "router"
      port: 80
      protocol: "TCP"
      targetPort: 8000
    - name: "router-ssl"
      port: 443
      protocol: "TCP"
      targetPort: 443
    selector:
      app.kubernetes.io/component: "router"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "router-gorouter-public"
    labels:
      app.kubernetes.io/component: "router-gorouter-public"
  spec:
    externalIPs:
    - "192.168.77.77"
    ports:
    - name: "router"
      port: 80
      protocol: "TCP"
      targetPort: 8000
    - name: "router-ssl"
      port: 443
      protocol: "TCP"
      targetPort: 443
    selector:
      app.kubernetes.io/component: "router"
kind: "List"
---
# The router instance group contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - gorouter: Gorouter maintains a dynamic routing table based on updates
#   received from NATS and (when enabled) the Routing API. This routing table
#   maps URLs to backends. The router finds the URL in the routing table that
#   most closely matches the host header of the request and load balances across
#   the associated backends.
#
# Also: bpm
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "router"
  labels:
    app.kubernetes.io/component: "router"
spec:
  podManagementPolicy: "Parallel"
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "router"
  serviceName: "router-set"
  template:
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: "router"
      name: "router"
    spec:
      containers:
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "FORCE_FORWARDED_PROTO_AS_HTTPS"
          value: "false"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "ROUTER_BALANCING_ALGORITHM"
          value: "round-robin"
        - name: "ROUTER_CLIENT_CERT_VALIDATION"
          value: "request"
        - name: "ROUTER_FORWARDED_CLIENT_CERT"
          value: "always_forward"
        - name: "ROUTER_SERVICES_SECRET"
          valueFrom:
            secretKeyRef:
              key: "router-services-secret"
              name: "secrets"
        - name: "ROUTER_SSL_CERT"
          valueFrom:
            secretKeyRef:
              key: "router-ssl-cert"
              name: "secrets"
        - name: "ROUTER_SSL_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "router-ssl-cert-key"
              name: "secrets"
        - name: "ROUTER_STATUS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "router-status-password"
              name: "secrets"
        - name: "ROUTER_TLS_PEM"
          valueFrom:
            secretKeyRef:
              key: "router-tls-pem"
              name: "secrets"
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_GOROUTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-gorouter-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: ""
        - name: "UAA_PORT"
          value: "2793"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-router:09321e0d31b46a8e4bd7ef6db212f5e79a048c32"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "router"
        ports:
        - containerPort: 8000
          name: "router"
          protocol: "TCP"
        - containerPort: 443
          name: "router-ssl"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/opt/fissile/readiness-probe.sh"
            - "curl --silent --fail --head http://${HOSTNAME}:8080/health"
        resources:
          requests:
            memory: "128Mi"
            cpu: "4000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      - env:
        - name: "AZ_LABEL_NAME"
          value: ""
        - name: "CATS_SUITES"
          value: ""
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "KUBERNETES_CLUSTER_DOMAIN"
          value: ""
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_AGENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert"
              name: "secrets"
        - name: "LOGGREGATOR_AGENT_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-agent-cert-key"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert"
              name: "secrets"
        - name: "LOGGREGATOR_FORWARD_CERT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-forward-cert-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PZ_LABEL_NAME"
          value: ""
        - name: "SCF_LOG_HOST"
          value: ""
        - name: "SCF_LOG_PORT"
          value: "514"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "VCAP_HARD_NPROC"
          value: "2048"
        - name: "VCAP_SOFT_NPROC"
          value: "1024"
        image: "registry.suse.com/cap/scf-loggregator-agent:39c7e06aaa613d8d7ae5ac05dc952c5d1cf1be17"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "loggregator-agent"
        ports: ~
        readinessProbe: ~
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/opt/fissile/config"
          name: "deployment-manifest"
          readOnly: true
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      serviceAccountName: "privileged"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "deployment-manifest"
        secret:
          secretName: "deployment-manifest"
          items:
          - key: "deployment-manifest"
            path: "deployment-manifest.yml"
