---
# Role binding for service account "default" and role "configgin-role"
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "default-configgin-role-binding"
  labels:
    app.kubernetes.io/component: "default-configgin-role-binding"
subjects:
- kind: "ServiceAccount"
  name: "default"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "configgin-role"
---
# Cluster role binding for service account "default" and cluster role
# "nonprivileged"
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRoleBinding"
metadata:
  name: "default-nonprivileged-cluster-binding"
  labels:
    app.kubernetes.io/component: "default-nonprivileged-cluster-binding"
subjects:
- kind: "ServiceAccount"
  name: "default"
  namespace: "~"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "nonprivileged"
