---
# Cluster role "eirini-role" used by accounts:
# - eirini
# - eirini-privileged
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "eirini-role"
  labels:
    app.kubernetes.io/component: "eirini-role"
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
