---
# Cluster role "withsysresource" used by accounts:
# - withsysresource
# - withsysresource-privileged
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "ClusterRole"
metadata:
  name: "withsysresource"
  labels:
    app.kubernetes.io/component: "withsysresource"
rules:
- apiGroups:
  - "extensions"
  resourceNames:
  - "withsysresource"
  resources:
  - "podsecuritypolicies"
  verbs:
  - "use"
